### ISSUE TITLE
Missing File requirements.txt

### ISSUE THREAD

**Issue by bmurch** [sat-utils/sat-fetch#8]
Hello all,
I have installed sat-search. It seems to work fine.
sat-search search --print-md -c landsat-8-l1 --bbox -79 25.5 -80.3 27.5 --datetime 2019-10-08
3 items found
Items (3):
date                      id
2019-10-08                LC80140432019281
2019-10-08                LC80140422019281
2019-10-08                LC80140412019281

Below is the error I get when trying to install sat-fetch. Any help is appreciated.:

[bmurch@optics0 sat-fetch-0.1.0rc1]$ pip3 install --user sat-fetch
Collecting sat-fetch
  Using cached https://files.pythonhosted.org/packages/bf/5f/b9b04a7f92a97ae4f1938067f100da6a217ff41375a4d659dcf23b276688/sat-fetch-0.1.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-izsoj7nb/sat-fetch/setup.py", line 12, in <module>
        with io.open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-izsoj7nb/sat-fetch/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-izsoj7nb/sat-fetch/

**Comment by matthewhanson** [comment]
hi @bmurch , looks like the requirements.txt file is missing from the deployment.  I'm adding a MANIFEST.in file to ensure that it is included and publishing a rc2 version.   Stay tuned.

**Comment by matthewhanson** [comment]
@bmurch that took longer than expected - CircleCI seemed to have made a change in the last few days and Docker layer caching isn't supported anymore on the free version.

Anyway, all published now, should install 0.1.0rc2.  I'd like to release a final version by the end of the month, so please open up any new issues if you come across anything!

Also note that there is a docker image you can use with all the dependencies installed if you run into problems.
```
docker fetch satutils/sat-fetch:0.1.0rc2
```
